version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: billinggiants
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/billinggiants -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
  api:
    profiles: ["dev"]
    build:
      context: ./server
      dockerfile: Dockerfile.local
    volumes:
      - ./server:/app
    ports:
      - "4000:4000"
    depends_on:
      - flyway
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/billinggiants?schema=public"
volumes:
  db: 